var template_status_loading = '<div id="fountainG">';
template_status_loading += '<div id="fountainG_1" class="fountainG"></div>';
template_status_loading += '<div id="fountainG_2" class="fountainG"></div>';
template_status_loading += '<div id="fountainG_3" class="fountainG"></div>';
template_status_loading += '<div id="fountainG_4" class="fountainG"></div>';
template_status_loading += '<div id="fountainG_5" class="fountainG"></div>';
template_status_loading += '<div id="fountainG_6" class="fountainG"></div>';
template_status_loading += '<div id="fountainG_7" class="fountainG"></div>';
template_status_loading += '<div id="fountainG_8" class="fountainG"></div>';
template_status_loading += '</div>';